-- wend-core: the graph model in portable SQLite.
--
-- This is the same graph the Postgres migrations in schema/ describe: a
-- per-user ontology (node_types, link_types, detail_definitions), the
-- instances built out of it (nodes, links, node_details, link_details,
-- node_aliases, tags), the provenance every committed fact points at
-- (sources), and the proposal queue an agent writes into instead of writing
-- to the graph (pending_writes, schema_proposals, conflicts). Column names,
-- value vocabularies and cascade behaviour are kept identical, so a graph can
-- be exported from one deployment and loaded into the other without a
-- translation step.
--
-- TENANCY IS THE ONE REAL DIFFERENCE
--
-- On Postgres the database holds many graphs, so tenancy is enforced by the
-- database: row level security is enabled on every table and each policy
-- checks user_id against the authenticated user. That policy layer is the
-- thing standing between two people's graphs.
--
-- A SQLite deployment is single tenant by construction. The database is one
-- file, that file belongs to one person, and there is no second graph in it to
-- reach. The same model therefore needs no policy layer here, and none is
-- defined. Access control moves out of the database and onto the things that
-- own the file: the filesystem permissions on it, and whatever the host puts
-- in front of the engine.
--
-- The user_id columns are kept anyway, for two reasons. A graph exported from
-- a multi-tenant deployment still filters correctly after it lands here, and
-- queries written against one deployment run unchanged on the other. Treat
-- them as a portability key, not as a boundary: nothing in this file enforces
-- them.
--
-- TYPE MAPPING
--
--   uuid          TEXT     canonical 36-character form, generated by the
--                          DEFAULT expression described below.
--   timestamptz   TEXT     ISO-8601 UTC with milliseconds, which is what
--                          strftime('%Y-%m-%dT%H:%M:%fZ','now') produces and
--                          what Date.toISOString() produces. These columns are
--                          sorted and compared as strings, so a different
--                          format reorders results rather than failing.
--   jsonb         TEXT     holding JSON. The engine parses on the way out.
--   uuid[]        TEXT     holding a JSON array of ids.
--   vector(1024)  BLOB     packed little-endian float32, one vector per row.
--   boolean       INTEGER  0 or 1.
--   numeric(3,2)  REAL     confidence only, where 0..1 needs no exact decimal.
--   enum          TEXT     plus the CHECK that lists the accepted values.
--
-- IDS
--
-- Every id defaults to a version 4 UUID built from randomblob(), so this file
-- is enough on its own: apply it with the sqlite3 shell and inserts that omit
-- an id still work, with no host-registered function required. A host that
-- prefers to generate ids itself can pass them explicitly and never touch the
-- default.
--
-- WHAT IS DELIBERATELY ABSENT
--
-- The row level security policies, for the reason above. The trigram indexes
-- on display_name and alias_text, and the ivfflat index on the embedding
-- column: SQLite has no equivalent for either, and neither has a substitute
-- worth faking. A leading-wildcard LIKE cannot use a b-tree index in any
-- engine, and vector recall here is an exact scan over the embedded rows, so
-- the useful thing to index is which rows those are.

pragma journal_mode = wal;

-- Foreign key enforcement is per connection in SQLite and defaults to off, so
-- this line only covers the connection that applies the file. Every connection
-- the engine opens has to set it too, or the on delete rules below are inert.
pragma foreign_keys = on;

-- ─────────────────────────────────────────────────────────────────────
-- Schema layer: the ontology, stored as rows rather than as DDL.
--
-- Built-in types are seeded when a graph is created. An agent extends the
-- vocabulary by proposal, or at confirm time when a write names a type that
-- does not exist yet; created_by_ai marks everything minted that way, so the
-- seeded vocabulary and the grown one stay tellable apart.
-- ─────────────────────────────────────────────────────────────────────

create table node_types (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  name text not null,
  description text,
  icon text,
  color text,
  is_builtin integer not null,
  created_by_ai integer not null default 0,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  unique (user_id, name)
);

create index node_types_user_idx on node_types (user_id);

create table link_types (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  name text not null,
  description text,
  direction text not null check (direction in ('directed', 'undirected')),
  -- How the reverse of a directed relation reads. Undirected types leave it null.
  inverse_name text,
  applies_to_source_type_id text references node_types (id) on delete set null,
  applies_to_target_type_id text references node_types (id) on delete set null,
  is_builtin integer not null,
  created_by_ai integer not null default 0,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  unique (user_id, name)
);

create index link_types_user_idx on link_types (user_id);
-- SQLite does not index foreign key columns for you, and an unindexed child
-- column makes every parent delete a full scan of this table.
create index link_types_source_type_idx on link_types (applies_to_source_type_id);
create index link_types_target_type_idx on link_types (applies_to_target_type_id);

create table detail_definitions (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  name text not null,
  description text,
  value_type text not null check (
    value_type in ('text', 'date', 'month_year', 'number', 'currency', 'url', 'enum', 'json')
  ),
  -- JSON. Carries the options list for an enum, the currency for a currency,
  -- and nothing for the plain types.
  value_config text,
  applies_to_node_type_id text references node_types (id) on delete cascade,
  applies_to_link_type_id text references link_types (id) on delete cascade,
  -- is_default attaches the field as a placeholder when a new instance of the
  -- type it belongs to is created.
  is_default integer not null default 0,
  is_builtin integer not null,
  created_by_ai integer not null default 0,
  -- multi_value keeps several live values instead of replacing the old one.
  -- Two email addresses are two facts, not a disagreement.
  multi_value integer not null default 0,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  -- A definition describes a field on a node type or on a link type, never both.
  check ((applies_to_node_type_id is not null) <> (applies_to_link_type_id is not null))
);

create index detail_definitions_user_idx on detail_definitions (user_id);
create index detail_definitions_node_type_idx on detail_definitions (applies_to_node_type_id)
  where applies_to_node_type_id is not null;
create index detail_definitions_link_type_idx on detail_definitions (applies_to_link_type_id)
  where applies_to_link_type_id is not null;

-- ─────────────────────────────────────────────────────────────────────
-- Provenance and labels.
-- ─────────────────────────────────────────────────────────────────────

-- Where a fact came from. Every node_details and link_details row references
-- one, and the reference is not nullable, so a committed fact whose origin
-- nobody can name is not representable.
--
-- source_type is an allowlist. A write naming a value outside it is rejected,
-- which means a new ingestion lane has to add its value here in the same
-- change that starts writing it.
create table sources (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  source_type text not null check (source_type in (
    'chat_message_text',
    'chat_message_voice',
    'screenshot',
    'image_upload',
    'audio_upload',
    'video_upload',
    'email_thread',
    'gmail_message',
    'web_search',
    'web_enrichment',
    'calendar_event',
    'user_typed',
    'mobile_share_sheet'
  )),
  -- What a person reading their own audit trail sees.
  display_label text not null,
  storage_path text,
  original_filename text,
  mime_type text,
  size_bytes integer,
  external_url text,
  metadata text,
  -- The passage a fact was read out of, kept so provenance can be shown rather
  -- than merely cited.
  context_text text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create index sources_user_created_idx on sources (user_id, created_at desc);

create table tags (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  name text not null,
  color text,
  is_builtin integer not null default 0,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  unique (user_id, name)
);

create index tags_user_idx on tags (user_id);

-- ─────────────────────────────────────────────────────────────────────
-- Instance layer: the graph itself.
-- ─────────────────────────────────────────────────────────────────────

create table nodes (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  -- restrict, not cascade: deleting a type that still has instances would take
  -- the people with it.
  node_type_id text not null references node_types (id) on delete restrict,
  display_name text not null,
  -- Packed little-endian float32. Null means not embedded yet, which is a
  -- normal state and not an error.
  embedding blob,
  notes text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create index nodes_user_type_idx on nodes (user_id, node_type_id);
create index nodes_user_display_name_idx on nodes (user_id, display_name);
-- Recall is an exact scan over the embedded rows, so the candidate set is the
-- only lever there is. This index is what makes that set cheap to enumerate.
create index nodes_user_embedded_idx on nodes (user_id) where embedding is not null;

create table links (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  link_type_id text not null references link_types (id) on delete restrict,
  source_node_id text not null references nodes (id) on delete cascade,
  target_node_id text not null references nodes (id) on delete cascade,
  notes text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Self-loops are legal. They are rare and usually a mistake, so a review
-- surface should question one, but the database is not the place to forbid it.
create index links_user_source_idx on links (user_id, source_node_id);
create index links_user_target_idx on links (user_id, target_node_id);
create index links_user_type_idx on links (user_id, link_type_id);

-- The fact values themselves, one row per fact, each carrying its source and a
-- confidence. user_confirmed marks the ones a person stood behind, which later
-- extraction is not allowed to overwrite. Deletion is soft, so an undo can
-- reach a fact after it is gone from every view.
create table node_details (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  node_id text not null references nodes (id) on delete cascade,
  detail_definition_id text not null references detail_definitions (id) on delete restrict,
  value text not null,
  -- When the fact was true, which is not when it was recorded. A former job is
  -- a fact with an end, not a fact that was wrong.
  valid_from text,
  valid_until text,
  confidence real not null default 1.0 check (confidence >= 0 and confidence <= 1),
  source_id text not null references sources (id) on delete restrict,
  user_confirmed integer not null default 0,
  deleted_at text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create index node_details_user_node_idx on node_details (user_id, node_id) where deleted_at is null;
create index node_details_user_def_idx on node_details (user_id, detail_definition_id) where deleted_at is null;
-- Answers "what did this source produce", which is the audit direction.
create index node_details_source_idx on node_details (source_id);

create table link_details (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  link_id text not null references links (id) on delete cascade,
  detail_definition_id text not null references detail_definitions (id) on delete restrict,
  value text not null,
  valid_from text,
  valid_until text,
  confidence real not null default 1.0 check (confidence >= 0 and confidence <= 1),
  source_id text not null references sources (id) on delete restrict,
  user_confirmed integer not null default 0,
  deleted_at text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create index link_details_user_link_idx on link_details (user_id, link_id) where deleted_at is null;
create index link_details_user_def_idx on link_details (user_id, detail_definition_id) where deleted_at is null;
create index link_details_source_idx on link_details (source_id);

-- Alternative names for a node: a nickname, a maiden name, a handle, a
-- spelling somebody heard rather than read. Recall and name matching read
-- these alongside display_name, so the second mention of a person lands on the
-- node that already exists instead of creating a second one.
create table node_aliases (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  node_id text not null references nodes (id) on delete cascade,
  alias_text text not null,
  source text not null default 'user'
    check (source in ('user', 'agent', 'extension', 'enrichment')),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  deleted_at text
);

-- Case-insensitive, which is the whole point of the index.
create unique index node_aliases_user_node_alias_idx
  on node_aliases (user_id, node_id, lower(alias_text)) where deleted_at is null;
create index node_aliases_user_idx on node_aliases (user_id) where deleted_at is null;

create table node_tags (
  user_id text not null,
  node_id text not null references nodes (id) on delete cascade,
  tag_id text not null references tags (id) on delete cascade,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  primary key (user_id, node_id, tag_id)
);

create index node_tags_user_tag_idx on node_tags (user_id, tag_id);

create table link_tags (
  user_id text not null,
  link_id text not null references links (id) on delete cascade,
  tag_id text not null references tags (id) on delete cascade,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  primary key (user_id, link_id, tag_id)
);

create index link_tags_user_tag_idx on link_tags (user_id, tag_id);

-- ─────────────────────────────────────────────────────────────────────
-- Governance: the queue an agent writes into, and the two questions the
-- engine refuses to answer on its own.
-- ─────────────────────────────────────────────────────────────────────

-- The session a batch of proposals came out of. It exists so a reviewer can
-- see what was being discussed when something was proposed. The transcript
-- itself is not part of the graph model and is not defined here.
create table conversations (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  started_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ended_at text,
  last_active_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  title text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create index conversations_user_active_idx on conversations (user_id, last_active_at desc);
create index conversations_user_open_idx on conversations (user_id, ended_at) where ended_at is null;

-- Agent-proposed graph writes, before they are graph writes.
--
-- Every mutation an agent asks for lands here as a row and reaches the graph
-- only through the confirm path, which applies the rows a person approved and
-- stamps committed_id with what it created. payload keeps the agent's original
-- proposal even when the person edited it, so what was proposed and what was
-- kept stay separately readable.
create table pending_writes (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  -- Groups everything proposed in one turn, so a review surface can present a
  -- turn as one decision rather than as a pile of rows.
  batch_id text not null,
  conversation_id text not null references conversations (id) on delete cascade,
  kind text not null check (kind in (
    'create_node',
    'create_link',
    'add_detail',
    'add_link_detail',
    'create_schema_proposal',
    'flag_conflict',
    'create_promise',
    'edit_node'
  )),
  payload text not null,
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'edited', 'rejected')),
  edited_payload text,
  committed_id text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  resolved_at text
);

create index pending_writes_batch_idx on pending_writes (batch_id);
create index pending_writes_user_status_idx on pending_writes (user_id, status);
create index pending_writes_conversation_idx on pending_writes (conversation_id, created_at);

-- Proposed additions to the ontology: a new node type, a new relationship, a
-- new field. reasoning is not optional, because a vocabulary change a person
-- cannot evaluate is one they can only rubber-stamp.
create table schema_proposals (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  proposal_type text not null check (proposal_type in (
    'node_type', 'link_type', 'detail_definition', 'subjective_scale', 'tag'
  )),
  proposed_payload text not null,
  reasoning text not null,
  -- JSON array of sources.id values.
  triggering_source_ids text,
  status text not null default 'pending' check (status in (
    'pending', 'approved', 'rejected', 'superseded'
  )),
  decision_notes text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  resolved_at text
);

create index schema_proposals_user_status_idx on schema_proposals (user_id, status, created_at desc);

-- Two sources disagree about the same fact. The row records both values with
-- the source each came from and waits. Nothing here picks a winner, and no
-- resolution is written without one being chosen, which is the point: a graph
-- that quietly resolves disagreements is a graph whose facts cannot be trusted
-- individually.
create table conflicts (
  id text primary key default (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',(random()&3)+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
  user_id text not null,
  target_kind text not null check (target_kind in ('node_detail', 'link_detail')),
  target_id text not null,
  existing_value text not null,
  existing_source_id text not null references sources (id) on delete cascade,
  incoming_value text not null,
  incoming_source_id text not null references sources (id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'resolved', 'ignored')),
  resolution text check (resolution in (
    'kept_existing', 'replaced_with_incoming', 'merged', 'both_valid_temporal'
  )),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  resolved_at text
);

create index conflicts_user_status_idx on conflicts (user_id, status, created_at desc);
create index conflicts_existing_source_idx on conflicts (existing_source_id);
create index conflicts_incoming_source_idx on conflicts (incoming_source_id);

-- ─────────────────────────────────────────────────────────────────────
-- updated_at maintenance.
--
-- Postgres does this with one trigger function reused by every table. SQLite
-- has no trigger functions, so each table carries its own statement trigger.
--
-- The WHEN clause is what keeps the trigger from re-entering itself when a
-- host has recursive_triggers on: the inner update changes updated_at, so on
-- the second pass new and old differ and the trigger does not fire again. It
-- also means a writer that sets updated_at explicitly is left alone.
-- ─────────────────────────────────────────────────────────────────────

create trigger nodes_touch_updated_at after update on nodes for each row
when new.updated_at = old.updated_at
begin
  update nodes set updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') where id = new.id;
end;

create trigger node_details_touch_updated_at after update on node_details for each row
when new.updated_at = old.updated_at
begin
  update node_details set updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') where id = new.id;
end;

create trigger link_details_touch_updated_at after update on link_details for each row
when new.updated_at = old.updated_at
begin
  update link_details set updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') where id = new.id;
end;

-- Schema version, read with PRAGMA user_version. A migration runner that
-- applies this file sets it; the statement is here so applying the file by
-- hand leaves the same marker.
pragma user_version = 1;
